---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: cloudflare-buypass
spec:
  acme:
    email: luca@rickli.cloud
    server: https://api.buypass.com/acme/directory
    privateKeySecretRef:
      name: cloudflare-issuer-acme-account-key
    solvers:
      - dns01:
          cloudflare:
            apiTokenSecretRef:
              name: cloudflare-dns
              key: api-token
